### PR TITLE
Unlock all event songs/charas/items by faking update at start.

### PR DESCRIPTION
**Pull request by flameCmndr**

### CODE REVIEW

**Comment by avail** [comment]
This should be a toggle if anything

**Comment by flameCmndr** [comment]
Sure, but just to be clear, these are songs that can't be unlocked by playing the base game. These are songs essentially hidden to the player because the game never checks its downloaded data until the cab goes into daily maintenance mode. During the event, the songs are added to the game and once the event is over, the songs remain in the players inventory.

**Comment by avail** [comment]
ahh these are the event ones. I misread, thought it was _all_ content

**Comment by flameCmndr** [comment]
Yeah, only the event songs. The chapter songs you still need to buy in game.

**Comment by hlcws** [comment]
Just to be clear this should contain songs from Touhou, Railgun, etc.?

**Pull request merged**
